spring:
  application:
    name: SpringBootKeycloak
  profiles:
    active: local
---

server:
  port: 8085

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.3.2:7029/auth/realms/colombo
          jwk-set-uri: http://192.168.3.2:7029/auth/realms/colombo/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: spring-client-api
      principle-attribute: preferred_username

logging:
  level:
    org:
      keycloak: DEBUG
